apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-technologies
  annotations:
    github.com/project-slug: omoyal/terroir-technologies
spec:
  type: other
  lifecycle: development
  owner: omoyal
